/*
 * Array of cipher objects
 *
 * Fields
 * name        String        Mandatory     display name
 * ref         String        Mandatory     reference used
 * alphabet    String        Optional      alphabet used
 * cleandec    Boolean       Optional      clean encrypted message before decodig
 * codealph    String        Optional      alphabet used for cleaning encrypted message
 *                                         standard alphabet used when missing
 * keepcase    Boolean       Optional      do not convert to uppercase when encoding/decoding
 * keepdiac    Boolean       Optional      keep diacretics when encoding
 * repl        Boolean       Optional      default setting for replacing characters when encoding
 * replchar    String        Optional      default characters to be replaced when encoding
 * keepunkn    Boolean       Optional      do not remove unknown characters when encoding/decoding
 * nodecode    Boolean       Optional      disable decode button
 * noencode    Boolean       Optional      disable encode button
 * keys        Array         Optional      all keys (or none)
 *   type      Boolean       String        txt, num, sel, chk - exactly one of these
 *   dflt                    Optional      default ref of key, match type
 *   min                     Optional      minimum of range when type = num
 *   max                     Optional      maximum of range when type = num
 *   sels      Array         Optional      selections used, mandatory when type = sel
 *    ref    Text          Mandatory     ref for ref
 *    label    Text          Mandatory     text to be displayed
 *   req       Boolean       Optional      mandatory key, used in validating keys
 *   showgen   Boolean       Optional      show button to generate polybiussquare
 *   clean     Boolean       Optional      clean the key using alphabet before using
 *
 *  All optional booleans are considered false when missing.
 */

export const ciphers = [
  {
    name: "ADFGV(X)",
    ref: "adfgvx",
    alphabet: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: true,
    replchar: "J=I",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        clean: true,
      },
    ],
  },
  {
    name: "Affine",
    ref: "affine",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "num",
        min: 1,
        max: 9999999,
        dflt: 5,
      },
      {
        type: "num",
        min: 1,
        dflt: 1,
      },
    ],
  },
  {
    name: "Amsco",
    ref: "amsco",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        clean: true,
        req: true,
      },
    ],
  },
  {
    name: "Atbash",
    ref: "atbash",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: true,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: true,
    keys: [],
  },
  {
    name: "A-tom-tom",
    ref: "atomtom",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    codealph: "/ ",
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [],
  },
  {
    name: "Autokey",
    ref: "autokey",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        clean: true,
      },
    ],
  },
  {
    name: "Bacon",
    ref: "bacon",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "num",
        dflt: 1,
        min: 1,
        max: 2,
      },
      {
        type: "txt",
        dflt: "A",
        req: true,
      },
      {
        type: "txt",
        dflt: "B",
        req: true,
      },
    ],
  },
  {
    name: "Base31",
    ref: "gcid",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
    cleandec: false,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [],
  },
  {
    name: "Bazeries",
    ref: "bazeries",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: true,
    replchar: "J=I",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        dflt: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
        req: true,
        showgen: true,
      },
      {
        type: "txt",
        dflt: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
        req: true,
        showgen: true,
      },
      {
        type: "num",
        req: true,
        min: 1,
        dflt: 12345,
      },
    ],
  },
  {
    name: "Beaufort",
    ref: "beaufort",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        clean: true,
      },
    ],
  },
  {
    name: "Bibi-binary",
    ref: "bibibinary",
    alphabet: "0123456789 ",
    cleandec: false,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [],
  },
  {
    name: "Bifid",
    ref: "bifid",
    alphabet: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: true,
    replchar: "J=I",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        clean: true,
      },
    ],
  },
  {
    name: "Burrows-Wheeler",
    ref: "burrowswheeler",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        dflt: "#"
      },
    ],
  },
  {
    name: "Cadenus",
    ref: "cadenus",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        clean: true,
      },
    ],
  },
  {
    name: "Caesar",
    ref: "rot13",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: true,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: true,
    keys: [
      {
        type: "num",
        dflt: 13,
        min: 1,
      },
    ],
  },
  {
    name: "Chaocipher",
    ref: "chaocipher",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        dflt: "ABCDEFMNOPQRSGHIJKLTUVWXYZ",
        req: true,
      },
      {
        type: "txt",
        dflt: "PQRSTUVWXYZABCDEKLMNOFGHIJ",
        req: true,
      },
    ],
  },
  {
    name: "Collon",
    ref: "collon",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: true,
    replchar: "J=I",
    keepunkn: false,
    keys: [
      {
        type: "sel",
        sels: [
          { ref: "RFCL", label: "Row first, column last" },
          { ref: "RLCL", label: "Row last, column last" },
          { ref: "RFCF", label: "Row first, column first" },
          { ref: "RLCF", label: "Row lastm column first" },
          { ref: "CLRL", label: "Column last, row last" },
          { ref: "CLRF", label: "Column last, row first" },
          { ref: "CFRF", label: "Column first, row first" },
          { ref: "CFRL", label: "Column first, row last" },
        ],
        dflt: "RFCL",
      },
      {
        type: "txt",
        dflt: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
        showgen: true,
        req: true,
      },
      {
        type: "num",
        min: 1,
        dflt: 3,
      },
    ],
  },
  {
    name: "Columnar Transposition",
    ref: "columnartransposition",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        clean: true,
        req: true,
      },
    ],
  },
  {
    name: "Condi",
    ref: "condi",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        clean: true,
        req: true,
      },
      {
        type: "num",
        min: 0,
        dflt: 0,
      },
    ],
  },
  {
    name: "Digrafid",
    ref: "digrafid",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ#",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        clean: true,
        req: true,
      },
      {
        type: "txt",
        clean: true,
        req: true,
      },
      {
        type: "num",
        min: 1,
        dflt: 2,
      },
    ],
  },
  {
    name: "Foursquare",
    ref: "foursquare",
    alphabet: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: true,
    replchar: "J=I",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        dflt: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
        clean: true,
        showgen: true,
        req: true,
      },
      {
        type: "txt",
        dflt: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
        clean: true,
        showgen: true,
        req: true,
      },
    ],
  },
  {
    name: "Geocache ID",
    ref: "gcid",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
    cleandec: false,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [],
  },
  {
    name: "Goldbug",
    ref: "goldbug",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [],
  },
  {
    name: "Gromark",
    ref: "gromark",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        clean: true,
        req: true,
      },
      {
        type: "num",
        dflt: 12345,
        min: 11111,
        max: 99999,
        req: true,
      },
    ],
  },
  {
    name: "Gronsfeld",
    ref: "gronsfeld",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "num",
        min: 1,
        req: true,
      },
    ],
  },
  {
    name: "Kamasutra",
    ref: "vatsyayana",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        dflt: "ABCDEFGHIJKLM",
        clean: true,
        req: true,
      },
      {
        type: "txt",
        dflt: "NOPQRSTUVWXYZ",
        clean: true,
        req: true,
      },
    ],
  },
  {
    name: "Kenny code",
    ref: "kennycode",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    codealph: "mpf",
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [],
  },
  {
    name: "Monome-dinome",
    ref: "monomedinome",
    alphabet: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
    cleandec: true,
    codealph: "0123456789",
    keepcase: false,
    keepdiac: false,
    repl: true,
    replchar: "J=I,V=U",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        clean: true,
      },
      {
        type: "txt",
        clean: true,
        req: true,
      },
    ],
  },
  {
    name: "Morbit",
    ref: "morbit",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXZ0123456789.,?!-/:'();=@&\"",
    cleandec: true,
    codealph: "0123456789",
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        clean: true,
      },
    ],
  },
  {
    name: "Morse",
    ref: "morse",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXZ0123456789.,?!-/:'();=@&\"",
    cleandec: false,
    keepcase: true,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: true,
    keys: [],
  },
  {
    name: "Myszkowski",
    ref: "myszkowski",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: true,
    keepdiac: true,
    repl: false,
    replchar: "",
    keepunkn: true,
    keys: [
      {
        type: "txt",
        req: true,
        clean: true,
      },
    ],
  },
  {
    name: "Nicodemus",
    ref: "nicodemus",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        clean: true,
      },
    ],
  },
  {
    name: "Nihilist",
    ref: "nihilist",
    alphabet: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: false,
    keepdiac: false,
    repl: true,
    replchar: "J=I",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        dflt: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
        showgen: true,
        req: true,
        clean: true,
      },
      {
        type: "txt",
        req: true,
        clean: true,
      },
    ],
  },
  {
    name: "Nihilist Transposition",
    ref: "nihilisttransposition",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: true,
    keepdiac: true,
    repl: false,
    replchar: "",
    keepunkn: true,
    keys: [
      {
        type: "txt",
        req: true,
        clean: true,
      },
      {
        type: "sel",
        sels: [
          { ref: true, label: "Row" },
          { ref: false, label: "Column" },
        ],
      },
    ],
  },
  {
    name: "One Time Pad",
    ref: "onetimepad",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        clean: true,
      },
    ],
  },
  {
    name: "Phillips",
    ref: "phillips",
    alphabet: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: true,
    replchar: "J=I",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        dflt: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
        req: true,
        showgen: true,
        clean: true,
      },
    ],
  },
  {
    name: "Playfair",
    ref: "playfair",
    alphabet: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: true,
    replchar: "J=I",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        dflt: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
        req: true,
        showgen: true,
        clean: true,
      },
    ],
  },
  {
    name: "Pollux",
    ref: "pollux",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        dflt: ".",
        req: true,
      },
      {
        type: "txt",
        dflt: "-",
        req: true,
      },
      {
        type: "txt",
        dflt: "x",
        req: true,
      },
    ],
  },
  {
    name: "Polybius",
    ref: "polybius",
    alphabet: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: false,
    keepdiac: false,
    repl: true,
    replchar: "J=I",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        dflt: "12345",
        req: true,
      },
      {
        type: "txt",
        dflt: "12345",
        req: true,
      },
    ],
  },
  {
    name: "Porta",
    ref: "porta",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
      },
    ],
  },
  {
    name: "Portax",
    ref: "portax",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        clean: true,
        req: true,
      },
    ],
  },
  {
    name: "Ragbaby",
    ref: "ragbaby",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        clean: true,
      },
    ],
  },
  {
    name: "Railfence",
    ref: "railfence",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: true,
    keepdiac: true,
    repl: false,
    replchar: "",
    keepunkn: true,
    keys: [
      {
        type: "num",
        dflt: 3,
        min: 1,
      },
      {
        type: "num",
        dflt: 0,
        min: 0,
      },
    ],
  },
  {
    name: "Redefence",
    ref: "redefence",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: true,
    keepdiac: true,
    repl: false,
    replchar: "",
    keepunkn: true,
    keys: [
      {
        type: "num",
        dflt: 3,
        min: 1,
      },
      {
        type: "num",
        dflt: 0,
        min: 0,
      },
      {
        type: "num",
        dflt: 123,
        min: 1,
      },
    ],
  },
  {
    name: "Reverse",
    ref: "reverse",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: true,
    keepdiac: true,
    repl: false,
    replchar: "",
    keepunkn: true,
    keys: [],
  },
  {
    name: "Reverse words",
    ref: "reversewords",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: true,
    keepdiac: true,
    repl: false,
    replchar: "",
    keepunkn: true,
    keys: [],
  },
  {
    name: "ROT5",
    ref: "rot5",
    alphabet: "0123456789",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "num",
        min: 0,
        dflt: 5,
      },
    ],
  },
  {
    name: "ROT13",
    ref: "rot13",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: true,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: true,
    keys: [
      {
        type: "num",
        min: 0,
        dflt: 13,
      },
    ],
  },
  {
    name: "ROT47",
    ref: "rot47",
    alphabet:
      "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "num",
        min: 0,
        dflt: 47,
      },
    ],
  },
  {
    name: "Scytale",
    ref: "scytale",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "num",
        min: 1,
        dflt: 3,
      },
    ],
  },
  {
    name: "Skip",
    ref: "skip",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: true,
    keepdiac: true,
    repl: false,
    replchar: "",
    keepunkn: true,
    keys: [
      {
        type: "num",
        min: 1,
        dflt: 3,
      },
      {
        type: "num",
        min: 1,
        dflt: 1,
      },
    ],
  },
  {
    name: "Substitution",
    ref: "substitution",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: false,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        dflt: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
      },
    ],
  },
  {
    name: "Syllabary",
    ref: "syllabary",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
    cleandec: true,
    codealph: "0123456789",
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
      },
      {
        type: "txt",
        dflt: "0123456789",
        req: true,
      },
      {
        type: "txt",
        dflt: "0123456789",
        req: true,
      },
    ],
  },
  {
    name: "Tapir",
    ref: "tapir",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    codealph: "0123456789",
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [],
  },
  {
    name: "Trisquare",
    ref: "trisquare",
    alphabet: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        dflt: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
        showgen: true,
      },
      {
        type: "txt",
        req: true,
        dflt: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
        showgen: true,
      },
      {
        type: "txt",
        req: true,
        dflt: "ABCDEFGHIKLMNOPQRSTUVWXYZ",
        showgen: true,
      },
    ],
  },
  {
    name: "Vatsyayana",
    ref: "vatsyayana",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        clean: true,
        dflt: "ABCDEFGHIJKLM",
      },
      {
        type: "txt",
        req: true,
        clean: true,
        dflt: "NOPQRSTUVWXYZ",
      },
    ],
  },
  {
    name: "Vigenere",
    ref: "vigenere",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        clean: true,
      },
    ],
  },
  {
    name: "Zebra",
    ref: "zebra",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    codealph: "0123456789",
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [],
  },
  {
    name: "Zygazyfa",
    ref: "zygazyfa",
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    cleandec: true,
    keepcase: false,
    keepdiac: false,
    repl: false,
    replchar: "",
    keepunkn: false,
    keys: [
      {
        type: "txt",
        req: true,
        clean: true,
      },
    ],
  },
];
