export const fontdefs = [
  { id: 'Antiker', font: 'Ancient (Star Gate)' },
  { id: 'Applebeech', font: 'Applebeech (runes)' },
  { id: 'Aurebesh', font: 'Aurebesh (Star Wars)' },
  { id: 'Barbook', font: 'Barbook' },
  { id: 'Betamaze', font: 'Betamaze' },
  { id: 'Braille', font: 'Braille' },
  { id: 'Centauri', font: 'Centauri (Babylon 5)' },
  { id: 'Code128', font: 'Code 128 (barcode)' },
  { id: 'Code39', font: 'Code 39 (barcode)' },
  { id: 'Cirth', font: 'Cirth Erebor (Tolkien)' },
  { id: 'Daedra', font: 'Daedra (The Elder Scrolls)' },
  { id: 'Dagger', font: 'Dagger' },
  { id: 'Dovahkiin', font: 'Dovahzul (The Elder Scrolls)' },
  { id: 'Drazi', font: 'Drazi (Babylon 5)' },
  { id: 'Eldfuth', font: 'Elder Futhark (runes)' },
  { id: 'Efkolia', font: 'Efkolia' },
  { id: 'FaceIt', font: 'Face it!' },
  { id: 'Fakoo', font: 'Fakoo (braille)' },
  { id: 'Fetish', font: 'Fetish (shoes)' },
  { id: 'Futurama', font: 'Futurama alien' },
  { id: 'Gallifreyan', font: 'Gallifreyan (Dr. Who)' },
  { id: 'Hylian64', font: 'Hylian 64 (Zelda)'},
  { id: 'HylianAn', font: 'Hylian, Ancient (Zelda)'},
  { id: 'HylianSS', font: 'Hylian, Skyward Sword (Zelda)'},
  { id: 'HylianTP', font: 'Hylian, Twilight Princess (Zelda)'},
  { id: 'Kix', font: 'Kix Code (PostNL)' },
  { id: 'Klingon', font: 'Klingon (Star Trek)' },
  { id: 'Klinzhai', font: 'Klinzhai (Star Trek)' },
  { id: 'Mandalor', font: 'Mandalorian (Star Wars)' },
  { id: 'Matoran', font: 'Matoran (Lego Bionicles)' },
  { id: 'Minbari', font: 'Minbari (Babylon 5)' },
  { id: 'Moonalpha', font: 'Moon Alphabet' },
  { id: 'Moonrunes', font: 'Moon Runes' },
  { id: 'Narn', font: 'Narn (Babylon 5)' },
  { id: 'Nycto', font: 'Nyctographic (Alice in Wonderland)'},
  { id: 'Ogham', font: 'Ogham (Medieval)' },
  { id: 'Pigpen', font: 'Pigpen cipher' },
  { id: 'Quadoo', font: 'Quadoo' },
  { id: 'Semaphore', font: 'Semaphore (flags)' },
  { id: 'TengwarA', font: 'Tengwar Annatar (Tolkien)' },
  { id: 'Templar', font: 'Templar Cipher' },
  { id: 'Tengo', font: 'Tengo' },
  { id: 'Theban', font: 'Theban' },
  { id: 'Unown', font: 'Unown' },
  { id: 'Utopian', font: 'Utopian' },
  { id: 'Visitor', font: 'Visitor (2009)' },
  { id: 'Vorlon', font: 'Vorlon (Babylon 5)' },
  { id: 'Vulcan', font: 'Vulcan script' },
  { id: 'Wakandan', font: 'Wakandan' }
]

