/*
 * Library to convert units
 *
 * Units are defined relative to a base unit (which is always the first in the array)
 * with the formula baseunit = unit * factor + offset
 *              e.g.  1 mile    = ( 1609.344 * 1 + 0 ) meter 
 *              e.g.  5 Kelvin  = ( 1 * 5 - 273.15   ) Celsius
 */


 export const definedUnits = [

    {
      category : "length",
      units : [
        { name: "Meter",                       symbol: "m",          factor: 1,                   offset: 0       },
        { name: "Angstrom",                    symbol: "Å",          factor: 1E-10,               offset: 0       },
        { name: "Arshin (old Russian)",        symbol: "arshin",     factor: 0.71120000000,       offset: 0       },
        { name: "Astronomical unit",           symbol: "AU",         factor: 149597870700,        offset: 0       },
        { name: "Barleycorn (imperial)",       symbol: "barleycorn", factor: 8.4666667E-3,        offset: 0       },
        { name: "Bohr",                        symbol: "a0",         factor: 5.291772E-11,        offset: 0       },
        { name: "Centimeter",                  symbol: "cm",         factor: 1E-2,                offset: 0       },
        { name: "Cable (imperial)",            symbol: "cable",      factor: 182.88000000000,     offset: 0       },
        { name: "Cable (imperial alt)",        symbol: "cable",      factor: 185.20000000000,     offset: 0       },
        { name: "Cable (US customary)",        symbol: "cable",      factor: 219.45600000,        offset: 0       },
        { name: "Chain (imperial)",            symbol: "chain",      factor: 20.1168,             offset: 0       },
        { name: "Cubit (imperial)",            symbol: "cubit",      factor: 0.4572,              offset: 0       },
        { name: "Decimeter",                   symbol: "dm",         factor: 1E-1,                offset: 0       },
        { name: "Dekameter",                   symbol: "dam",        factor: 1E1,                 offset: 0       },
        { name: "Digit (imperial)",            symbol: "digit",      factor: 0.019050000,         offset: 0       },
        { name: "Ell (imperial)",              symbol: "ell",        factor: 1.14300000000,       offset: 0       },
        { name: "Foot",                        symbol: "ft",         factor: 0.3048,              offset: 0       },
        { name: "Foot (US survey)",            symbol: "ft",         factor: 0.30480061,          offset: 0       },
        { name: "Fathom (imperial)",           symbol: "fath",       factor: 1.8288,              offset: 0       },
        { name: "Fathom (imperial alt)",       symbol: "fath",       factor: 1.8520,              offset: 0       },
        { name: "Finger (imperial)",           symbol: "finger",     factor: 0.02222500000,       offset: 0       },
        { name: "Furlong (imperial)",          symbol: "fur",        factor: 201.168,             offset: 0       },
        { name: "Gigameters",                  symbol: "Gm",         factor: 1E9,                 offset: 0       },
        { name: "Grade (imperial)",            symbol: "grade",      factor: 1.52400000000,       offset: 0       },
        { name: "Hand (imperial)",             symbol: "hand",       factor: 0.1016,              offset: 0       },
        { name: "Hectometer",                  symbol: "hm",         factor: 1E2,                 offset: 0       },
        { name: "Inch",                        symbol: "in",         factor: 0.0254,              offset: 0       },
        { name: "Kilometer",                   symbol: "km",         factor: 1E3,                 offset: 0       },
        { name: "League (imperial)",           symbol: "league",     factor: 4828.0320000000,     offset: 0       },
        { name: "Light years",                 symbol: "ly",         factor: 9460528404879400,    offset: 0       },
        { name: "Ligne (old French)",          symbol: "ligne",      factor: 0.00225555556,       offset: 0       },
        { name: "Line (imperial)",             symbol: "ly",         factor: 0.00211666667,       offset: 0       },
        { name: "Link (imperial)",             symbol: "link",       factor: 0.20116800000,       offset: 0       },
        { name: "Mickey",                      symbol: "NA",         factor: 0.000127,            offset: 0       },
        { name: "Micrometers",                 symbol: "μm",         factor: 1E-6,                offset: 0       },
        { name: "Microns",                     symbol: "μ",          factor: 1E-6,                offset: 0       },
        { name: "Mil (US)",                    symbol: "mil",        factor: 0.0254E-3,           offset: 0       },
        { name: "Mile (imperial)",             symbol: "mi",         factor: 1609.344,            offset: 0       },
        { name: "Mile (US survey)",            symbol: "mi",         factor: 1609.347,            offset: 0       },
        { name: "Millimeter",                  symbol: "mm",         factor: 1E-3,                offset: 0       },
        { name: "Nail (imperial)",             symbol: "mm",         factor: 0.05715000000,       offset: 0       },
        { name: "Nanometers",                  symbol: "nm",         factor: 1E-9,                offset: 0       },
        { name: "Nautical mile (imperial)",    symbol: "nmi",        factor: 1852,                offset: 0       },
        { name: "Nautical mile (admirality)",  symbol: "nmi (adm)",  factor: 1853.248,            offset: 0       },
        { name: "Pace (imperial)",             symbol: "pace",       factor: 0.76200000000,       offset: 0       },
        { name: "Palm (imperial)",             symbol: "palm",       factor: 0.0762,              offset: 0       },
        { name: "Parsecs",                     symbol: "pc",         factor: 30856775812800000,   offset: 0       },
        { name: "Perch (imperial)",            symbol: "rd",         factor: 5.02920000000,       offset: 0       },
        { name: "Pica (imperial)",             symbol: "pica",       factor: 0.0042333333333333,  offset: 0       },
        { name: "Picometer",                   symbol: "pm",         factor: 1E-12,               offset: 0       },
        { name: "Pied du roi (old French)",    symbol: "pied",       factor: 0.3248,              offset: 0       },
        { name: "Point (Didot French)",        symbol: "point",      factor: 0.37597200000,       offset: 0       },
        { name: "Point (imperial)",            symbol: "pt",         factor: 0.00035277778,       offset: 0       },
        { name: "Point (Postscript)",          symbol: "pt",         factor: 0.0003527,           offset: 0       },
        { name: "Point (old French)",          symbol: "point",      factor: 0.00018796296,       offset: 0       },
        { name: "Point (EU)",                  symbol: "point",      factor: 0.37606500000,       offset: 0       },
        { name: "Pole (imperial)",             symbol: "rd",         factor: 5.02920000000,       offset: 0       },
        { name: "Poppyseed (imperial)",        symbol: "pt",         factor: 0.00211666667,       offset: 0       },
        { name: "Potrzebie (comic)",           symbol: "potrzebie",  factor: 2.263348517438173216473E-3, offset: 0,        },
        { name: "Pouce (old French)",          symbol: "pouce",      factor: 0.027066667,         offset: 0       },
        { name: "Quarter (imperial)",          symbol: "qt",         factor: 0.2286,              offset: 0       },
        { name: "Rod (imperial)",              symbol: "rd",         factor: 5.02920000000,       offset: 0       },
        { name: "Rope (imperial)",             symbol: "rope",       factor: 6.096,               offset: 0       },
        { name: "Sazhen (old Russian)",        symbol: "sazhen",     factor: 2.13360000000,       offset: 0       },
        { name: "Shaftment (imperial)",        symbol: "shaftment",  factor: 0.15240000000,       offset: 0       },
        { name: "Shaku (Japan)",               symbol: "尺",         factor: 0.3030303,           offset: 0       },
        { name: "Skein (imperial)",            symbol: "skein",      factor: 109.72800000000,     offset: 0       },
        { name: "Span (imperial)",             symbol: "span",       factor: 0.2286,              offset: 0       },
        { name: "Spat",                        symbol: "spat",       factor: 1E12,                offset: 0       },
        { name: "Spindle (imperial)",          symbol: "spindle",    factor: 13167.36000000,      offset: 0       },
        { name: "Step (imperial)",             symbol: "step",       factor: 1.52400000000,       offset: 0       },
        { name: "Stick (imperial)",            symbol: "stick",      factor: 0.0508,              offset: 0       },
        { name: "Toise (old French)",          symbol: "toise",      factor: 1.94903631,          offset: 0       },
        { name: "Thou (imperial)",             symbol: "thou",       factor: 0.0254E-3,           offset: 0       },
        { name: "Twip (imperial)",             symbol: "twip",       factor: 0.000017638,         offset: 0       },
        { name: "Verst (old Russian)",         symbol: "verst",      factor: 1066.8,              offset: 0,        }, 
        { name: "Yard",                        symbol: "yd",         factor: 0.9144,              offset: 0       }
      ]
    },

    {
      category : "area",
      units: [
        { name: "Square meter",          symbol: "m²",          factor: 1,                            offset: 0,        },
        { name: "Acre (imperial)",       symbol: "ac",          factor: 4046.85642240,                offset: 0,        },
        { name: "Acre (US survey)",      symbol: "ac",          factor: 4046.872,                     offset: 0,        },
        { name: "Are",                   symbol: "a",           factor: 1E2,                          offset: 0,        },
        { name: "Barn",                  symbol: "b",           factor: 1E-27,                        offset: 0,        },
        { name: "Barony",                symbol: "barony",      factor: 1.618743e7,                   offset: 0,        },
        { name: "Board",                 symbol: "bd",          factor: 0.00774192,                   offset: 0,        },
        { name: "Bovate (15 acres)",     symbol: "bovate",      factor: 60702.84633600,               offset: 0,        },
        { name: "Carucate (120 acres)",  symbol: "bovate",      factor: 485622.77068800,              offset: 0,        },
        { name: "Centiare",              symbol: "ca",          factor: 1,                            offset: 0,        },
        { name: "Cents",                 symbol: "ct",          factor: 40.468564224,                 offset: 0,        },
        { name: "Cord",                  symbol: "cord",        factor: 1.486449,                     offset: 0,        },
        { name: "Cuerda",                symbol: "cda",         factor: 3930.396,                     offset: 0,        },
        { name: "Dunam",                 symbol: "dunam",       factor: 1000,                         offset: 0,        },
        { name: "Guntha (India)",        symbol: "guntha",      factor: 101.17,                       offset: 0,        },
        { name: "Hectare",               symbol: "ha",          factor: 1E4,                          offset: 0,        },
        { name: "Hide (120 acres)",      symbol: "hide",        factor: 485622.72,                    offset: 0,        },
        { name: "Homestead (US Survey)", symbol: "homestead",   factor: 647499.4416,                  offset: 0,        },
        { name: "Perch (imperial)",      symbol: "perch",       factor: 25.29285264,                  offset: 0,        },
        { name: "Ping",                  symbol: "ping",        factor: 3.306,                        offset: 0,        },
        { name: "Rood (imperial)",       symbol: "ro",          factor: 1011.714,                     offset: 0,        },
        { name: "Section (US survey)",   symbol: "section",     factor: 2589997.766,                  offset: 0,        },
        { name: "Square Angstom",        symbol: "Å²",          factor: 1E-20,                        offset: 0,        },
        { name: "Square Astronomical Unit",  symbol: "AU²",     factor: 22379536647199999918080,      offset: 0,        },
        { name: "Square Centimeter",     symbol: "cm²",         factor: 1E-4,                         offset: 0,        },
        { name: "Square Decimeter",      symbol: "dm²",         factor: 1E-2,                         offset: 0,        },
        { name: "Square Dekameter",      symbol: "dam²",        factor: 1E2,                          offset: 0,        },
        { name: "Square Fathoms",        symbol: "NA",          factor: 3.34450944,                   offset: 0,        },
        { name: "Square Feet",           symbol: "ft²",         factor: 0.09290304,                   offset: 0,        },
        { name: "Square Hectometer",     symbol: "hm²",         factor: 1E4,                          offset: 0,        },
        { name: "Square Inches",         symbol: "in²",         factor: 0.00064516,                   offset: 0,        },
        { name: "Square kilometer",      symbol: "km²",         factor: 1E6,                          offset: 0,        },
        { name: "Square Micrometer",     symbol: "μm²",         factor: 1E-12,                        offset: 0,        },
        { name: "Square Microns",        symbol: "NA",          factor: 1E-12,                        offset: 0,        },
        { name: "Square Mile",           symbol: "mi²",         factor: 2589988.110336,               offset: 0,        },
        { name: "Square Millimeter",     symbol: "mm²",         factor: 1E-6,                         offset: 0,        },
        { name: "Square Nanometer",      symbol: "nm²",         factor: 1E-18,                        offset: 0,        },
        { name: "Square Parsecs",        symbol: "NA",          factor: 952141195522860048533913451102208,   offset: 0, },
        { name: "Square Rod (imperial)", symbol: "NA",          factor: 25.29285264,                  offset: 0,        },
        { name: "Square Yards",          symbol: "yd²",         factor: 0.83612736,                   offset: 0,        },
        { name: "Township (US survey)",  symbol: "township",    factor: 93239919.59,                  offset: 0,        },
        { name: "Virgate (30 acres)",    symbol: "virgate",     factor: 121405.69267200,              offset: 0,        },
        { name: "Yardland (30 acres)",   symbol: "yardland",    factor: 121405.69267200,              offset: 0,        }
      ]
    },

    {
      // https://en.wikipedia.org/wiki/Cooking_weights_and_measures#United_States_measures
      // http://www.handy2lz.com/converters/volume_converters.html
      // https://en.wikipedia.org/wiki/English_wine_cask_units
      
      category: "vol",
      units: [
        { name: "Liter",                   symbol: "l",           factor: 1,                          offset: 0,        },
        { name: "Acre-foot",               symbol: "acre-ft",     factor: 1233481.83754752,           offset: 0,        },
        { name: "Barrel (imperial)",       symbol: "bl (imp)",    factor: 163.6592,                   offset: 0,        },
        { name: "Barrel (petroleum)",      symbol: "bbl",         factor: 158.9873,                   offset: 0,        },
        { name: "Barrel (UK wine)",        symbol: "bl",          factor: 119.3348625,                offset: 0,        },
        { name: "Barrel (US customary dry)",   symbol: "bl (us)",     factor: 115.6282,               offset: 0,        },
        { name: "Barrel (US customary fluid)", symbol: "fl bl (us)",  factor: 119.2405,               offset: 0,        },
        { name: "Bucket (imperial)",       symbol: "bkt",         factor: 18.18436,                   offset: 0,        },
        { name: "Bushel (imperial)",       symbol: "bu (imp)",    factor: 36.36872,                   offset: 0,        },
        { name: "Bushel (imperial 1824)",  symbol: "bu (imp)",    factor: 36.34965427,                offset: 0,        },
        { name: "Bushel (dry heaped)",     symbol: "bu (us)",     factor: 44.04884,                   offset: 0,        },
        { name: "Bushel (dry level)",      symbol: "bu (us)",     factor: 35.23907,                   offset: 0,        },
        { name: "Butt (UK wine)",          symbol: "butt",        factor: 477.33945,                  offset: 0,        },
        { name: "Butt (US wine)",          symbol: "butt",        factor: 476.961884784,              offset: 0,        },
        { name: "Centiliter",              symbol: "cl",          factor: 0.01,                       offset: 0,        },
        { name: "Coffeespoon (US)",        symbol: "csp.",        factor: 1.84835E-3,                 offset: 0,        },
        { name: "Coomb",                   symbol: "coomb",       factor: 145.4749,                   offset: 0,        },
        { name: "Cord (firewood)",         symbol: "cord",        factor: 3624.556,                   offset: 0,        },
        { name: "Cubic centimeter",        symbol: "cm³",         factor: 1E-3,                       offset: 0,        },
        { name: "Cubic decimeter",         symbol: "dm³",         factor: 1,                          offset: 0,        },
        { name: "Cubic foot",              symbol: "ft³",         factor: 28.31684592,                offset: 0,        },
        { name: "Cubic inch",              symbol: "in³",         factor: 0.016387064,                offset: 0,        },
        { name: "Cubic meter",             symbol: "m³",          factor: 1E3,                        offset: 0,        },
        { name: "Cubic yard",              symbol: "yd³",         factor: 764.554847984,              offset: 0,        },
        { name: "Cup (imperial)",          symbol: "c (uk)",      factor: 284.1E-3,                   offset: 0,        },
        { name: "Cup (metric)",            symbol: "c",           factor: 0.25,                       offset: 0,        },
        { name: "Cup (US customary)",      symbol: "c (us)",      factor: 0.2365882365,               offset: 0,        },
        { name: "Cup (US nutrition)",      symbol: "c (us)",      factor: 0.24,                       offset: 0,        },
        { name: "Dash (imperial)",         symbol: "ds",          factor: 0.36996175130208E-3,        offset: 0,        },
        { name: "Dash (US)",               symbol: "ds",          factor: 0.30805759960938E-3,        offset: 0,        },
        { name: "Deciliter",               symbol: "dl",          factor: 0.1,                        offset: 0,        },
        { name: "Dessertspoon (imperial)", symbol: "dsp",         factor: 118.387760416667E-3,        offset: 0,        },
        { name: "Drop (imperial)",         symbol: "gtt",         factor: 0.098656467013889E-3,       offset: 0,        },
        { name: "Drop (medical)",          symbol: "gtt",         factor: 0.083333333333333E-3,       offset: 0,        },
        { name: "Drop (metric)",           symbol: "gtt",         factor: 0.05E-3,                    offset: 0,        },
        { name: "Drop (US)",               symbol: "gtt",         factor: 0.082148693229167E-3,       offset: 0,        },
        { name: "Firkin (UK brewery)",     symbol: "firkin",      factor: 40.91481,                   offset: 0,        },
        { name: "Fluid drachm (imperial)",     symbol: "dr",      factor: 3.5516328125E-3,            offset: 0,        },
        { name: "Fluid drachm (US customary)", symbol: "dr",      factor: 3.6966911953125E-3,         offset: 0,        },
        { name: "Fluid ounce (imperial)",  symbol: "fl oz",       factor: 28.4130625E-3,              offset: 0,        },
        { name: "Fluid ounce (US customary)", symbol: "fl oz",    factor: 29.5735295625E-3,           offset: 0,        },
        { name: "Fluid ounce (US nutrition)", symbol: "fl oz",    factor: 30E-3,                      offset: 0,        },
        { name: "Fluid scruple (imperial)", symbol: "fl oz",      factor: 1.18387760416E-3,           offset: 0,        },
        { name: "Gallon (imperial)",       symbol: "gal",         factor: 4.54609,                    offset: 0,        },
        { name: "Gallon (imperial 1824)",  symbol: "gal",         factor: 4.543706784,                offset: 0,        },
        { name: "Gallon (US dry)",         symbol: "gal",         factor: 4.40488377086,              offset: 0,        },
        { name: "Gallon (US fluid)",       symbol: "gal",         factor: 3.785411784,                offset: 0,        },
        { name: "Gill (imperial)",         symbol: "tcf",         factor: 142.0653125E-3,             offset: 0,        },
        { name: "Gill (imperial 1824)",    symbol: "tcf",         factor: 141.990837E-3,              offset: 0,        },
        { name: "Gill (US customary)",     symbol: "tcf",         factor: 118.29411825E-3,            offset: 0,        },
        { name: "Hogshead (imperial)",     symbol: "hhd",         factor: 327.31848,                  offset: 0,        }, 
        { name: "Hogshead (UK brewery)",   symbol: "hhd",         factor: 245.48886000,               offset: 0,        },
        { name: "Hogshead (UK wine)",      symbol: "hhd",         factor: 238.669725,                 offset: 0,        },
        { name: "Hogshead (US customary)", symbol: "hhd",         factor: 238.480942392,              offset: 0,        },
        { name: "Jack (imperial)",         symbol: "jack",        factor: 0.070995418,                offset: 0,        },
        { name: "Kilderkin (UK brewery)",  symbol: "kilderkin",   factor: 81.82962,                   offset: 0,        },
        { name: "Lambda",                  symbol: "λ",           factor: 1E-6,                       offset: 0,        },
        { name: "Last (Dutch)",            symbol: "last",        factor: 3398,                       offset: 0,        },
        { name: "Last (imperial)",         symbol: "last",        factor: 2909.498,                   offset: 0,        },
        { name: "Milliliter",              symbol: "ml",          factor: 0.001,                      offset: 0,        },
        { name: "Minim (imperial)",        symbol: "min",         factor: 0.05919388E-3,              offset: 0,        },
        { name: "Minim (US)",              symbol: "min",         factor: 0.061611519921875E-3,       offset: 0,        },
        { name: "Peck (imperial)",         symbol: "pk",          factor: 9.09218,                    offset: 0,        },
        { name: "Peck (imperial 1824)",    symbol: "pk",          factor: 9.087413567,                offset: 0,        },
        { name: "Peck (US dry)",           symbol: "pk",          factor: 8.80976754172,              offset: 0,        },
        { name: "Pinch (imperial)",        symbol: "pn",          factor: 0.73992350260417E-3,        offset: 0,        },
        { name: "Pinch (US)",              symbol: "pn",          factor: 0.61611519921875E-3,        offset: 0,        },
        { name: "Pint (imperial)",         symbol: "pt",          factor: 568.26125E-3,               offset: 0,        },
        { name: "Pint (imperial 1824)",    symbol: "pt",          factor: 567.963348E-3,              offset: 0,        },
        { name: "Pint (US dry)",           symbol: "pt",          factor: 550.6104713575E-3,          offset: 0,        },
        { name: "Pint (US fluid)",         symbol: "pt",          factor: 473.17647E-3,               offset: 0,        },
        { name: "Pony (US fluid)",         symbol: "pt",          factor: 22.180147171875E-3,         offset: 0,        },
        { name: "Pottle (imperial)",       symbol: "pot",         factor: 2.273045,                   offset: 0,        },
        { name: "Pottle (US customary)",   symbol: "pot",         factor: 1.8927058920,               offset: 0,        },
        { name: "Puncheon (UK wine)",      symbol: "puncheon",    factor: 317.974589856,              offset: 0,        },
        { name: "Puncheon (US wine)",      symbol: "puncheon",    factor: 318.2263,                   offset: 0,        },
        { name: "Quart (imperial)",        symbol: "qt",          factor: 1.1365225,                  offset: 0,        },
        { name: "Quart (imperial 1824)",   symbol: "qt",          factor: 1.135926696,                offset: 0,        },
        { name: "Quart (US dry)",          symbol: "qt",          factor: 1.101220942715,             offset: 0,        },
        { name: "Quart (US fluid)",        symbol: "qt",          factor: 0.946352946,                offset: 0,        },
        { name: "Quarter (imperial)",      symbol: "qtr",         factor: 290.9497600,                offset: 0,        },
        { name: "Quarter (imperial 1824)", symbol: "qtr",         factor: 290.7972341,                offset: 0,        },
        { name: "Rundlet (UK wine)",       symbol: "rundlet",     factor: 68.19,                      offset: 0,        },
        { name: "Rundlet (US wine)",       symbol: "rundlet",     factor: 68.14,                      offset: 0,        },
        { name: "Shot (US customary)",     symbol: "shot",        factor: 0.0443602943,               offset: 0,        },
        { name: "Strike (imperial)",       symbol: "strike",      factor: 72.73744,                   offset: 0,        },
        { name: "Strike (US customary)",   symbol: "strike",      factor: 70.47814033,                offset: 0,        },
        { name: "Tablespoon (imperial)",   symbol: "tbsp",        factor: 17.75816E-3,                offset: 0,        },
        { name: "Tablespoon (imperial alt)", symbol: "tbsp",      factor: 14.206531E-3,               offset: 0,        },
        { name: "Tablespoon (metric)",     symbol: "tbsp",        factor: 15E-3,                      offset: 0,        },
        { name: "Tablespoon (US customary)",  symbol: "tbsp",     factor: 14.7868E-3,                 offset: 0,        },
        { name: "Tablespoon (US nutrition)",  symbol: "tbsp",     factor: 15E-3,                      offset: 0,        },
        { name: "Teaspoon (imperial)",     symbol: "tsp",         factor: 5.919388E-3,                offset: 0,        },
        { name: "Teaspoon (imperial alt)", symbol: "tsp",         factor: 4.73551E-3,                 offset: 0,        },
        { name: "Teaspoon (metric)",       symbol: "tsp",         factor: 5E-3,                       offset: 0,        },
        { name: "Teaspoon (US customary)", symbol: "tsp",         factor: 4.92892E-3,                 offset: 0,        },
        { name: "Teaspoon (US nutrition)", symbol: "tsp",         factor: 5E-3,                       offset: 0,        }, 
        { name: "Tierce (UK wine)",        symbol: "tierce",      factor: 159.11315,                  offset: 0,        }, 
        { name: "Tierce (US wine)",        symbol: "tierce",      factor: 158.987294928,              offset: 0,        }, 
        { name: "Tun (imperial)",          symbol: "tun",         factor: 954.6789,                   offset: 0,        }, 
        { name: "Tun (US)",                symbol: "tun",         factor: 953.923769568,              offset: 0,        }, 
        { name: "Wey (imperial)",          symbol: "wey",         factor: 1454.7488,                  offset: 0,        }, 
        { name: "Wey (US)",                symbol: "wey",         factor: 1409.5628066752,            offset: 0,        } 
      ]
    },

    {
      category: "temp",
      units: [
        { name: "Celsius",          symbol: "℃",          factor: 1,          offset: 0,        },
        { name: "Fahrenheit",       symbol: "℉",          factor: 0.555555555555555555555,    offset: -17.77777777777777777778,   },
        { name: "Kelvin",           symbol: "K",           factor: 1,          offset: -273.15,  },
        { name: "Rankine",          symbol: "°R",          factor: 0.555555555555555555555,    offset: -273.15,   },
        { name: "Delisle",          symbol: "°De",         factor: 0.666666666666666666667,    offset: 66.666666666666666666667,   },
        { name: "Newton",           symbol: "°N",          factor: 3.030303030303030303030,    offset: 0,        },
        { name: "Réaumur",          symbol: "°Ré",         factor: 1.25,       offset: 0,        },
        { name: "Rømer",            symbol: "°Rø",         factor: 1.904761904761904761905,    offset: -14.28571428571428571429,   }
      ]
    },

    {
      category: "power",
      units: [
        { name: "Watt",                               symbol: "W",          factor: 1,                    offset: 0,        }, 
        { name: "Donkeypower (comic)",                symbol: "NA",         factor: 250,                  offset: 0,        }, 
        { name: "Horsepower (electric)",              symbol: "hp",         factor: 746,                  offset: 0,        }, 
        { name: "Horsepower (imperial or mechanic)",  symbol: "hp",         factor: 745.69987158227,      offset: 0,        }, 
        { name: "Horsepower (metric)",                symbol: "hp",         factor: 735.49875,            offset: 0,        }, 
        { name: "Kilowatt",                           symbol: "kW",         factor: 1E3,                  offset: 0,        }, 
        { name: "Megawatt",                           symbol: "MW",         factor: 1E6,                  offset: 0,        }
      ]
    },

    {
      category: "mass",
      units: [
        { name: "Kilogram",                           symbol: "kg",         factor: 1,                    offset: 0,        }, 
        { name: "Berkovets (old Russian)",            symbol: "berkovets",  factor: 163.8068720000,       offset: 0,        },
        { name: "Carat",                              symbol: "ct",         factor: 200E-6,               offset: 0,        }, 
        { name: "Dolya (old Russian)",                symbol: "dolya",      factor: 44.3546E-6,           offset: 0,        }, 
        { name: "Drachm (imperial)",                  symbol: "dr",         factor: 0.06479891E-3,        offset: 0,        }, 
        { name: "Drachm (UK apothecary)",             symbol: "ʒ",          factor: 3.887934600E-3,       offset: 0,        }, 
        { name: "Funt (old Russian)",                 symbol: "funt",       factor: 409.51718E-3,         offset: 0,        },
        { name: "Gamma",                              symbol: "gamma",      factor: 1E-9,                 offset: 0,        }, 
        { name: "Grain (imperial)",                   symbol: "gr",         factor: 1.7718451953125E-3,   offset: 0,        }, 
        { name: "Gram",                               symbol: "g",          factor: 1E-3,                 offset: 0,        }, 
        { name: "Libra (ancient Roman)",              symbol: "libra",      factor: 328.9E-3,             offset: 0,        },
        { name: "Lot (old Russian)",                  symbol: "lot",        factor: 12.79741188E-3,       offset: 0,        },
        { name: "Ounce (imperial)",                   symbol: "oz",         factor: 28.349523125E-3,      offset: 0,        }, 
        { name: "Ounce (UK apothecary)",              symbol: "℥",          factor: 31.103476800E-3,      offset: 0,        }, 
        { name: "Pound (imperial)",                   symbol: "lb",         factor: 0.45359237,           offset: 0,        }, 
        { name: "Pound (UK apothecary)",              symbol: "℔",          factor: 373.241721600E-3,     offset: 0,        }, 
        { name: "Stone (imperial)",                   symbol: "st",         factor: 6.35029318,           offset: 0,        }, 
        { name: "Pennyweight (troy)",                 symbol: "dwt",        factor: 1.55517384E-3,        offset: 0,        }, 
        { name: "Quarter (imperial)",                 symbol: "qr",         factor: 12.70058636,          offset: 0,        }, 
        { name: "Hundredweight (imperial)",           symbol: "cwt",        factor: 50.80234544,          offset: 0,        }, 
        { name: "Hundredweight (US customary)",       symbol: "cwt",        factor: 45.359237000,         offset: 0,        }, 
        { name: "Obolus (ancient Roman)",             symbol: "obolus",     factor: 0.571006944E-3,       offset: 0,        },
        { name: "Pood (old Russian)",                 symbol: "pood",       factor: 16.38068720000,       offset: 0,        },
        { name: "Scruple (UK apothecary)",            symbol: "℈",          factor: 1.295978200E-3,       offset: 0,        }, 
        { name: "Scrupulum (ancient Roman)",          symbol: "scrupulum",  factor: 1.142013889E-3,       offset: 0,        },
        { name: "Semuncia (ancient Roman)",           symbol: "semuncia",   factor: 13.704166667E-3,      offset: 0,        },
        { name: "Semisextula (ancient Roman)",        symbol: "semisextula",factor: 2.284027778E-3,       offset: 0,        },
        { name: "Sextula (ancient Roman)",            symbol: "sextula",    factor: 4.568055556E-3,       offset: 0,        },
        { name: "Siliqua (ancient Roman)",            symbol: "siliqua",    factor: 0.190335648E-3,       offset: 0,        },
        { name: "Slug (imperial)",                    symbol: "slug",       factor: 14.59390293883,       offset: 0,        }, 
        { name: "Ton (metric)",                       symbol: "t",          factor: 1E3,                  offset: 0,        }, 
        { name: "Ton (imperial)",                     symbol: "t",          factor: 1016.0469088,         offset: 0,        }, 
        { name: "Ton (US customary)",                 symbol: "t",          factor: 907.184740000,        offset: 0,        }, 
        { name: "Troy ounce (troy)",                  symbol: "oz t",       factor: 31.103476800E-3,      offset: 0,        }, 
        { name: "Troy pound (troy)",                  symbol: "lb t",       factor: 373.241721600E-3,     offset: 0,        }, 
        { name: "Uncia (ancient Roman)",              symbol: "uncia",      factor: 27.408333333E-3,      offset: 0,        },
        { name: "Zolotnik (old Russian)",             symbol: "zolotnik",   factor: 4.26580396E-3,        offset: 0,        }
      ]
    },

    {
      category: "angle",
      units: [
        { name: "Degree",                             symbol: "°",          factor: 1,                    offset: 0,        }, 
        { name: "Arcminute",                          symbol: "minute",     factor: 0.01666666666667,     offset: 0,        }, 
        { name: "Arcsecond",                          symbol: "second",     factor: 0.0002777777777778,   offset: 0,        }, 
        { name: "Circle (full)",                      symbol: "circle",     factor: 360,                  offset: 0,        }, 
        { name: "Furman",                             symbol: "furman",     factor: 0.0054931640625,      offset: 0,        }, 
        { name: "Grad",                               symbol: "^g",         factor: 0.9,                  offset: 0,        }, 
        { name: "Gon",                                symbol: "gon",        factor: 0.9,                  offset: 0,        }, 
        { name: "Mil or streck (NATO)",               symbol: "mil",        factor: 0.05625,              offset: 0,        }, 
        { name: "Mil or streck (Warsaw pact)",        symbol: "mil",        factor: 0.06,                 offset: 0,        }, 
        { name: "Mil or streck (Swedish army)",       symbol: "mil",        factor: 0.05714285,           offset: 0,        }, 
        { name: "Radians",                            symbol: "rad",        factor: 57.29577951308,       offset: 0,        }, 
        { name: "Revolution",                         symbol: "revolution", factor: 360,                  offset: 0,        }, 
        { name: "Sextant",                            symbol: "sextant",    factor: 60,                   offset: 0,        }, 
        { name: "Sign (astrology)",                   symbol: "sign",       factor: 30,                   offset: 0,        }, 
        { name: "Turn",                               symbol: "turn",       factor: 360,                  offset: 0,        }, 
      ]       
    },

    {
      category: "speed",
      units: [
        { name: "Meter/second",                       symbol: "m/s",          factor: 1,                    offset: 0,        }, 
        { name: "Earth's velocity",                   symbol: "NA",           factor: 29765,                offset: 0,        }, 
        { name: "Foot/hour",                          symbol: "ft/h",         factor: 0.00008466666666667,  offset: 0,        }, 
        { name: "Foot/minute",                        symbol: "ft/min",       factor: 0.00508,              offset: 0,        }, 
        { name: "Foot/second",                        symbol: "ft/s",         factor: 0.3048,               offset: 0,        }, 
        { name: "Kilometer/hour",                     symbol: "km/h",         factor: 0.2777777777778,      offset: 0,        }, 
        { name: "Kilometer/minute",                   symbol: "km/min",       factor: 16.666666666667,      offset: 0,        }, 
        { name: "Kilometer/second",                   symbol: "km/s",         factor: 1000,                 offset: 0,        }, 
        { name: "Knot",                               symbol: "m/h",          factor: 0.5144444444444,      offset: 0,        }, 
        { name: "Knot (UK)",                          symbol: "m/h",          factor: 0.5147733333333,      offset: 0,        }, 
        { name: "Mach",                               symbol: "Ma",           factor: 295.0464000003,       offset: 0,        }, 
        { name: "Meter/hour",                         symbol: "m/h",          factor: 0.0002777777777778,   offset: 0,        }, 
        { name: "Meter/minute",                       symbol: "m/min",        factor: 0.01666666666667,     offset: 0,        },
        { name: "Mile/hour",                          symbol: "mi/h",         factor: 0.44704,              offset: 0,        }, 
        { name: "Mile/minute",                        symbol: "mi/min",       factor: 26.8224,              offset: 0,        }, 
        { name: "Mile/second",                        symbol: "mi/s",         factor: 1609.344,             offset: 0,        }, 
        { name: "Yard/hour",                          symbol: "yd/h",         factor: 0.000254,             offset: 0,        }, 
        { name: "Yard/minute",                        symbol: "yd/min",       factor: 0.01524,              offset: 0,        }, 
        { name: "Yard/second",                        symbol: "yd/s",         factor: 0.9144,               offset: 0,        }        
      ]       
    },

    {
      category: "time",
      units: [
        { name: "Second",                             symbol: "s",            factor: 1,                    offset: 0,        }, 
        { name: "Day",                                symbol: "day",          factor: 86400.000,            offset: 0,        },
        { name: "Dekasecond",                         symbol: "das",          factor: 10,                   offset: 0,        }, 
        { name: "Fortnight",                          symbol: "fortnight",    factor: 1209600.0,            offset: 0,        },
        { name: "Helek, Chelek, Halakim (Hebrew)",    symbol: "helek",        factor: 3.3333333333333,      offset: 0,        }, 
        { name: "Hour",                               symbol: "h",            factor: 3600,                 offset: 0,        },
        { name: "Jiffy (electronics 60Hz)",           symbol: "jiffy",        factor: 0.01666666667,        offset: 0,        }, 
        { name: "Jiffy (electronics 50Hz)",           symbol: "jiffy",        factor: 0.02,                 offset: 0,        }, 
        { name: "Kermit",                             symbol: "kermit",       factor: 864,                  offset: 0,        }, 
        { name: "Microcentury",                       symbol: "microcentury", factor: 3155.700,             offset: 0,        },
        { name: "Microsecond",                        symbol: "µs",           factor: 1E-6,                 offset: 0,        }, 
        { name: "Millisecond",                        symbol: "ms",           factor: 1E-3,                 offset: 0,        }, 
        { name: "Minute",                             symbol: "min",          factor: 60,                   offset: 0,        }, 
        { name: "Month (30 days)",                    symbol: "month",        factor: 2592000.000,          offset: 0,        },
        { name: "Month (Hebrew calendar)",            symbol: "month",        factor: 2551443.3333333,      offset: 0,        },
        { name: "Nanocentury",                        symbol: "nanocentury",  factor: 3.156,                offset: 0,        }, 
        { name: "Nanosecond",                         symbol: "ns",           factor: 1E-9,                 offset: 0,        }, 
        { name: "Pahar, Prahar, Peher (India)",       symbol: "pahar",        factor: 10800.000,            offset: 0,        },
        { name: "Shake",                              symbol: "shake",        factor: 1E-8,                 offset: 0,        }, 
        { name: "Svedberg",                           symbol: "svedberg",     factor: 1E-13,                offset: 0,        }, 
        { name: "Week",                               symbol: "wk",           factor: 604800.00,            offset: 0,        },
        { name: "Year (365 days)",                    symbol: "yr",           factor: 31536000.00,          offset: 0,        },
        { name: "Year (Gregorian)",                   symbol: "yr",           factor: 31556952.00,          offset: 0,        },
        { name: "Year (Hebrew calendar)",             symbol: "yr",           factor: 31557325.439,         offset: 0,        },
        { name: "Year (Julian)",                      symbol: "yr",           factor: 31557600.00,          offset: 0,        },
        { name: "Year (leap 366 days)",               symbol: "yr",           factor: 31622400.00,          offset: 0,        },
        { name: "Year (tropical)",                    symbol: "yr",           factor: 31556925.216,         offset: 0,        }
      ]       
    }

 ]

 export function convertUnit (val, cat, idfrom, idto) {

  // First convert to baseunit
  let temp = val * definedUnits[cat].units[idfrom].factor + definedUnits[cat].units[idfrom].offset;
  
  // Return conversion from baseunit
  return (temp - definedUnits[cat].units[idto].offset) / definedUnits[cat].units[idto].factor;
 

 }