import { createRouter, createWebHistory } from 'vue-router'

const routes = [
  { path: '/',                    name: 'home',                  component: () => import('@/views/HomePage.vue')  },
  { path: "/alltools",            name: 'AllTools',              component: () => import('@/components/AllTools.vue') },
  { path: "/convert",             name: 'Convert',               component: () => import('@/components/coords/Convert.vue') },
  { path: "/project",             name: 'Project',               component: () => import('@/components/coords/Project.vue') },
  { path: "/lines",               name: 'Lines',                 component: () => import('@/components/coords/Lines.vue') },
  { path: "/triangles",           name: 'Triangles',             component: () => import('@/components/coords/Triangles.vue') },
  { path: "/circles",             name: 'Circles',               component: () => import('@/components/coords/Circles.vue') },
  { path: "/incomplete",          name: 'Incomplete',            component: () => import('@/components/coords/Incomplete.vue') },
  { path: "/antipode",            name: 'Antipode',              component: () => import('@/components/coords/Antipode.vue') },
  { path: "/mapmaker",            name: 'MapMaker',              component: () => import('@/components/coords/MapMaker.vue') },
  { path: "/w3w",                 name: 'W3W',                   component: () => import('@/components/coords/W3W.vue') },
  { path: "/revwherigo",          name: 'RevWherigo',            component: () => import('@/components/coords/RevWherigo.vue') },
  { path: "/tryanswers",          name: 'TryAnswers',            component: () => import('@/components/texts/TryAnswers.vue') },
  { path: "/wordvalue",           name: 'WordValue',             component: () => import('@/components/texts/WordValue.vue') },
  { path: "/analtxt",             name: 'AnalTxt',               component: () => import('@/components/texts/AnalTxt.vue') },
  { path: "/texttonum",           name: 'TextToNum',             component: () => import('@/components/texts/TextToNum.vue') },
  { path: "/charcodes",           name: 'CharCodes',             component: () => import('@/components/texts/CharCodes.vue') },
  { path: "/keyboards",           name: 'Keyboards',             component: () => import('@/components/texts/Keyboards.vue') },
  { path: "/texttoss",            name: 'TextToss',              component: () => import('@/components/texts/TextToss.vue') },
  { path: "/textchunks",          name: 'TextChunks',            component: () => import('@/components/texts/TextChunks.vue') },
  { path: "/numerology",          name: 'Numerology',            component: () => import('@/components/texts/Numerology.vue') },
  { path: '/ciphers/:cphr?',      name: 'Ciphers',               component: () => import('@/components/codes/Ciphers.vue'),  },
  { path: '/rotciphers',          name: 'RotCiphers',            component: () => import('@/components/codes/RotCiphers.vue')  },
  { path: "/substcipher",         name: 'SubstCipher',           component: () => import('@/components/codes/SubstCipher.vue') },
  { path: "/codebook/:code?",     name: 'Codebook',              component: () => import('@/components/codes/CodeBook.vue') },   
  { path: "/fonts/:font?",        name: 'Fonts',                 component: () => import('@/components/codes/Fonts.vue') },
  { path: "/segment",             name: 'Segment',               component: () => import('@/components/codes/Segment.vue')},
  { path: "/resistor",            name: 'Resistor',              component: () => import('@/components/codes/Resistor.vue')},
  { path: "/decabit",             name: 'DecaBit',               component: () => import('@/components/codes/DecaBit.vue')},
  { path: '/freqanal',            name: 'FreqAnal',              component: () => import('@/components/codes/FreqAnalysis.vue')  },
  { path: "/baseconv",            name: 'BaseConv',              component: () => import('@/components/math/BaseConv.vue') },
  { path: "/digits",              name: 'Digits',                component: () => import('@/components/math/Digits.vue') },
  { path: "/primes",              name: 'Primes',                component: () => import('@/components/math/Primes.vue')},
  { path: "/romans",              name: 'Romans',                component: () => import('@/components/math/Romans.vue')},
  { path: "/formulasolv",         name: 'FormulaSolver',         component: () => import('@/components/math/FormulaSolver.vue')},
  { path: "/numberprop",          name: 'NumberProp',            component: () => import('@/components/math/NumberProp.vue') },
  { path: "/fibonacci",           name: 'Fibonacci',             component: () => import('@/components/math/Fibonacci.vue') },
  { path: "/bignumbers",          name: 'BigNumbers',            component: () => import('@/components/math/BigNumbers.vue') },
  { path: "/nimbers",             name: 'Nimbers',               component: () => import('@/components/math/Nimbers.vue') },
  { path: "/gcdandlcm",           name: 'GCDAndLCM',             component: () => import('@/components/math/GCDandLCM.vue') },
  { path: "/palindrome",          name: 'Palindrome',            component: () => import('@/components/math/Palindrome.vue') },
  { path: "/sequences",           name: 'Sequences',             component: () => import('@/components/math/Sequences.vue') },
  { path: "/bcd",                 name: 'bcd',                   component: () => import('@/components/comp/BCD.vue') },
  { path: "/encryption",          name: 'encryption',            component: () => import('@/components/comp/Encryption.vue') }, //Param: enc is name of the initial encryption
  { path: "/hashes",              name: 'hashes',                component: () => import('@/components/comp/Hashes.vue') },     //Param: hash is name of the initial encryption
  { path: "/brainfuck",           name: 'brainfuck',             component: () => import('@/components/comp/Brainfuck.vue') },  //Param: bfvar is name of the initial BF variation
  { path: "/deadfish",            name: 'deadfish',              component: () => import('@/components/comp/Deadfish.vue') },
  { path: "/cow",                 name: 'cow',                   component: () => import('@/components/comp/Cow.vue') },
  { path: "/beatnik",             name: 'beatnik',               component: () => import('@/components/comp/Beatnik.vue') },
  { path: "/bintotext",           name: 'bintotext',             component: () => import('@/components/comp/BinToText.vue') },
  { path: "/duckspeak",           name: 'duckspeak',             component: () => import('@/components/comp/Duckspeak.vue') },
  { path: "/checksum",            name: 'checksum',              component: () => import('@/components/comp/Checksum.vue') } ,
  { path: '/printlog',            name: 'PrintLog',              component: () => import('@/components/other/PrintLog.vue')      },
  { path: '/sudokusolv',          name: 'SudokuSolv',            component: () => import('@/components/other/SudokuSolv.vue')      },
  { path: '/mmsolver',            name: 'MMSolver',              component: () => import('@/components/other/MMSolver.vue') },
  { path: '/periodictable',       name: 'PeriodicTable',         component: () => import('@/components/other/PeriodicTable.vue')    },
  { path: '/countries',           name: 'Countries',             component: () => import('@/components/other/Countries.vue')    },
  { path: '/htmlparser',          name: 'HtmlParser',            component: () => import('@/components/other/HtmlParser.vue')  },
  { path: '/unitconvertor',       name: 'UnitConvertor',         component: () => import('@/components/other/UnitConvertor.vue')    },
  { path: '/usastates',           name: 'UsaStates',             component: () => import('@/components/other/UsaStates.vue')      },
  { path: '/regions',             name: 'Regions',               component: () => import('@/components/other/Regions.vue')   },
  { path: '/dnacode',             name: 'DNACode',               component: () => import('@/components/other/DNACode.vue')        }, 
  { path: '/datecalc',            name: 'DateCalc',              component: () => import('@/components/other/DateCalc.vue')        }, 
  { path: '/randomizer',          name: 'Randomizer',            component: () => import('@/components/other/Randomizer.vue')        }, 
  { path: '/gameoflife',          name: 'GameOfLife',            component: () => import('@/components/other/GameOfLife.vue')        }, 
  { path: '/booksearch',          name: 'BookSearch',            component: () => import('@/components/other/BookSearch.vue')        }, 
  { path: '/exifscanner',         name: 'ExifScanner',           component: () => import('@/components/images/ExifScanner.vue')      },
  { path: '/colorpicker',         name: 'ColorPicker',           component: () => import('@/components/images/ColorPicker.vue')      },
  { path: '/filltool',            name: 'FillTool',              component: () => import('@/components/images/FillTool.vue')         },
  { path: '/pixeldata',           name: 'PixelData',             component: () => import('@/components/images/PixelData.vue')        },
  { path: '/pixelbuild',          name: 'PixelBuild',            component: () => import('@/components/images/PixelBuild.vue')       },
  { path: '/imagetransform',      name: 'ImageTransform',        component: () => import('@/components/images/ImageTransform.vue')   },
  { path: '/textextractor',       name: 'TextExtractor',         component: () => import('@/components/images/TextExtractor.vue')    },
  { path: '/howto',               name: 'HowTo',                 component: () => import('@/views/HowTo.vue')},
  { path: '/helptext',            name: 'HelpText',              component: () => import('@/components/texts/TextTools.vue')  },
  { path: '/helpmath',            name: 'HelpMath',              component: () => import('@/components/math/MathTools.vue')  },
  { path: '/helpimage',           name: 'HelpImage',             component: () => import('@/components/images/ImageTools.vue')  },
  { path: '/helpother',           name: 'HelpOther',             component: () => import('@/components/other/OtherIntro.vue')  },
  { path: '/helpcodes',           name: 'HelpCodes',             component: () => import('@/components/codes/CodesIntro.vue')  },
  { path: '/helpcomp',            name: 'HelpComp',              component: () => import('@/components/comp/CompTools.vue')  },
  { path: '/helpcoord',           name: 'HelpCoord',             component: () => import('@/components/coords/CoordTools.vue')  },
  { path: '/about',               name: 'About',                 component: () => import('@/views/AboutPage.vue')  }
]

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes
})

export default router
