import { createRouter, createWebHistory } from 'vue-router'

const routes = [
  { path: '/',   name: 'home',  component: () => import('@/views/HomePage.vue')  },
  { path: "/alltools",        name: 'AllTools',         component: () => import('@/components/AllTools.vue') },
  { path: "/coordconvert",    name: 'CoordConvert',     component: () => import('@/components/coords/CoordConvert.vue') },
  { path: "/coordproj",       name: 'CoordProj',        component: () => import('@/components/coords/CoordProject.vue') },
  { path: "/coordlines",      name: 'CoordLines',       component: () => import('@/components/coords/CoordLines.vue') },
  { path: "/coordtriangles",  name: 'CoordTriangles',   component: () => import('@/components/coords/CoordTriangles.vue') },
  { path: "/coordcircles",    name: 'CoordCircles',     component: () => import('@/components/coords/CoordCircles.vue') },
  { path: "/coordincomplete", name: 'CoordIncomplete',  component: () => import('@/components/coords/CoordIncomplete.vue') },
  { path: "/coordantipode",   name: 'CoordAntipode',    component: () => import('@/components/coords/CoordAntipode.vue') },
  { path: "/coordmapmaker",   name: 'MapMaker',         component: () => import('@/components/coords/CoordMapMaker.vue') },
  { path: "/coordw3w",        name: 'CoordW3W',         component: () => import('@/components/coords/CoordW3W.vue') },
  { path: "/reversewherigo",  name: 'ReverseWherigo',   component: () => import('@/components/coords/ReverseWherigo.vue') },
  { path: "/textwordvalue",   name: 'WordValue',        component: () => import('@/components/texts/TextWordValue.vue') },
  { path: "/smartreplace",    name: 'SmartReplace',     component: () => import('@/components/texts/SmartReplace.vue') },
  { path: "/textanalyzer",    name: 'TextAnalyzer',     component: () => import('@/components/texts/TextAnalyze.vue') },
  { path: "/texttonumbers",   name: 'TextToNumbers',    component: () => import('@/components/texts/TextToNumbers.vue') },
  { path: "/textcodes",       name: 'TextCodes',        component: () => import('@/components/texts/TextCodes.vue') },
  { path: "/textkeyboards",   name: 'Keyboards',        component: () => import('@/components/texts/TextKeyboards.vue') },
  { path: "/texttoss",        name: 'TextToss',         component: () => import('@/components/texts/TextToss.vue') },
  { path: "/textnum",         name: 'Numerology',       component: () => import('@/components/texts/Numerology.vue') },
  { path: '/cipher/:cphr?',   name: 'Cipher',           component: () => import('@/components/codes/EncoderDecoder.vue'),  },
  { path: '/rotcipher',       name: 'RotCipher',        component: () => import('@/components/codes/RotCiphers.vue')  },
  { path: "/codebook",        name: 'Codebook',         component: () => import('@/components/codes/CodeBook.vue') },   
  { path: "/fonts",           name: 'Fonts',            component: () => import('@/components/codes/FontSpecial.vue') },
  { path: "/segment",         name: 'Segment',          component: () => import('@/components/codes/SegmentCode.vue')},
  { path: "/resistorcode",    name: 'Resistor',         component: () => import('@/components/codes/ResistorCode.vue')},
  { path: "/decabit",         name: 'DecaBit',          component: () => import('@/components/codes/DecaBit.vue')},
  { path: '/freqanal',        name: 'FreqAnal',         component: () => import('@/components/codes/FreqAnalysis.vue')  },
  { path: "/baseconvertor",     name: 'BaseConvertor',         component: () => import('@/components/math/MathBase.vue') },
  { path: "/countdigits",       name: 'Digits',                component: () => import('@/components/math/MathDigits.vue') },
  { path: "/primes",            name: 'Primes',                component: () => import('@/components/math/MathPrimes.vue')},
  { path: "/romans",            name: 'Romans',                component: () => import('@/components/math/MathRomans.vue')},
  { path: "/formulasolv",       name: 'FormulaSolver',         component: () => import('@/components/math/MathFormula.vue')},
  { path: "/numberproperties",  name: 'NumberProperties',      component: () => import('@/components/math/MathProperties.vue') },
  { path: "/fibonacci",         name: 'Fibonacci',             component: () => import('@/components/math/MathFib.vue') },
  { path: "/bignumbers",        name: 'BigNumbers',            component: () => import('@/components/math/MathBigNumbers.vue') },
  { path: "/nimbers",           name: 'Nimbers',               component: () => import('@/components/math/MathNimbers.vue') },
  { path: "/gcdandlcm",         name: 'GCDAndLCM',             component: () => import('@/components/math/MathGCDandLCM.vue') },
  { path: "/palindromecounter", name: 'Palindrome',            component: () => import('@/components/math/MathPalindrome.vue') },
  { path: "/sequences",         name: 'Sequences',             component: () => import('@/components/math/MathSequences.vue') },
  { path: "/charcodes",       name: 'charcodes',       component: () => import('@/components/texts/TextCodes.vue') },
  { path: "/bcd",             name: 'bcd',             component: () => import('@/components/comp/CompBCD.vue') },
  { path: "/encryption",      name: 'encryption',      component: () => import('@/components/comp/CompEncryption.vue') }, //Param: enc is name of the initial encryption
  { path: "/hashes",          name: 'hashes',          component: () => import('@/components/comp/CompHashes.vue') },     //Param: hash is name of the initial encryption
  { path: "/brainfuck",       name: 'brainfuck',       component: () => import('@/components/comp/CompBrainfuck.vue') },  //Param: bfvar is name of the initial BF variation
  { path: "/deadfish",        name: 'deadfish',        component: () => import('@/components/comp/CompDeadfish.vue') },
  { path: "/cow",             name: 'cow',             component: () => import('@/components/comp/CompCow.vue') },
  { path: "/beatnik",         name: 'beatnik',         component: () => import('@/components/comp/CompBeatnik.vue') },
  { path: "/bintotext",       name: 'compbintotext',   component: () => import('@/components/comp/CompBinToText.vue') },
  { path: "/duckspeak",       name: 'duckspeak',       component: () => import('@/components/comp/CompDuckspeak.vue') },
  { path: "/checksum",        name: 'checksum',        component: () => import('@/components/comp/CompChecksum.vue') } ,
  { path: '/printlog',        name: 'PrintLog',         component: () => import('@/components/other/PrintLog.vue')      },
  { path: '/sudokusolver',    name: 'SudokuSolver',     component: () => import('@/components/other/SudokuSolver.vue')      },
  { path: '/mmsolver',        name: 'MastermindSolver', component: () => import('@/components/other/MastermindSolver.vue') },
  { path: '/periodictable',   name: 'PeriodicTable',    component: () => import('@/components/other/PeriodicTable.vue')    },
  { path: '/countries',       name: 'CountriesAll',     component: () => import('@/components/other/CountriesAll.vue')    },
  { path: '/html',            name: 'HtmlParser',       component: () => import('@/components/other/HtmlParser.vue')  },
  { path: '/unitconvertor',   name: 'UnitConvertor',    component: () => import('@/components/other/UnitConvertor.vue')    },
  { path: '/usastates',       name: 'UsaStates',        component: () => import('@/components/other/UsaStates.vue')      },
  { path: '/countryregions',  name: 'CountryRegions',   component: () => import('@/components/other/CountryRegions.vue')   },
  { path: '/dnacode',         name: 'DNACode',          component: () => import('@/components/other/DNACode.vue')        }, 
  { path: '/datecalc',        name: 'DateCalc',         component: () => import('@/components/other/DateCalc.vue')        }, 
  { path: '/randomizer',      name: 'Randomizer',       component: () => import('@/components/other/Randomizer.vue')        }, 
  { path: '/gameoflife',      name: 'GameOfLife',       component: () => import('@/components/other/GameOfLife.vue')        }, 
  { path: '/booksearch',      name: 'BookSearch',       component: () => import('@/components/other/BookSearch.vue')        }, 
  { path: '/exifscanner',     name: 'ExifScanner',      component: () => import('@/components/images/ExifScanner.vue')      },
  { path: '/colorpicker',     name: 'ColorPicker',      component: () => import('@/components/images/ColorPicker.vue')      },
  { path: '/filltool',        name: 'FillTool',         component: () => import('@/components/images/FillTool.vue')         },
  { path: '/pixeldata',       name: 'PixelData',        component: () => import('@/components/images/PixelData.vue')        },
  { path: '/pixelbuild',      name: 'PixelBuild',       component: () => import('@/components/images/PixelBuild.vue')       },
  { path: '/imagetransform',  name: 'ImageTransform',   component: () => import('@/components/images/ImageTransform.vue')   },
  { path: '/textextractor',   name: 'TextExtractor',    component: () => import('@/components/images/TextExtractor.vue')    },
  { path: '/howto',           name: 'HowTo',            component: () => import('@/views/HowTo.vue')},
  { path: '/helptext',        name: 'HelpText',         component: () => import('@/components/texts/TextTools.vue')  },
  { path: '/helpmath',        name: 'HelpMath',         component: () => import('@/components/math/MathTools.vue')  },
  { path: '/helpimage',       name: 'HelpImage',        component: () => import('@/components/images/ImageTools.vue')  },
  { path: '/helpother',       name: 'HelpOther',        component: () => import('@/components/other/OtherIntro.vue')  },
  { path: '/helpcodes',       name: 'HelpCodes',        component: () => import('@/components/codes/CodesIntro.vue')  },
  { path: '/helpcomp',        name: 'HelpComp',         component: () => import('@/components/comp/CompTools.vue')  },
  { path: '/helpcoord',       name: 'HelpCoord',        component: () => import('@/components/coords/CoordTools.vue')  },
  { path: '/about',           name: 'About',            component: () => import('@/views/AboutPage.vue')  }
]

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes
})

export default router
